src/HappeningFree/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('events.urls', namespace="events")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/events/urls.py
from django.urls import path
from events.views import (
    HomePageView,
    SignUpView,
    DevelopmentView,
    AllEventsView,
    AddEventView,
    EventInformationView,
    EventJoinView,
    ProfileView,
    UserEventsView,
    EventDeleteView,
    ParticipantsListView,
    RecommendationView,
)

from django.contrib.auth.views import (
    LoginView,
    LogoutView
)

app_name = 'events'

urlpatterns = [
    path('', HomePageView, name='events-home'),
    path('signup/', SignUpView, name='events-signup'),
    path('inprogress', DevelopmentView, name='events-inprogress'),
    path('login/', LoginView.as_view(template_name='login.html'), name='events-login'),
    path('logout/', LogoutView.as_view(), name='events-logout'),
    path('allevents/', AllEventsView, name='events-allevents'),
    path('addevent/', AddEventView, name='events-addevent'),
    path('allevents/<int:event_id>/', EventInformationView, name='events-eventinfo'),
    path('allevents/<int:event_id>/delete/', EventDeleteView, name='events-eventdelete'),
    path('allevents/<int:event_id>/join/', EventJoinView, name='events-eventjoin'),
    path('profile/', ProfileView, name='events-profile'),
    path('myevents/', UserEventsView, name='events-myevents'),
    path('myevents/<int:event_id>/participants/', ParticipantsListView, name='events-participants'),
    path('reccomended/', RecommendationView, name='events-recommended'),
]

src/templates/addevent.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head %}
    <title>Happening Free - Add Event</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

{% endblock head %}

{% block body %}
<br>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
            <a class="btn btn-danger" href="{% url 'events:events-home' %}">Home</a>&nbsp; &nbsp;
            <a class="btn btn-danger" href="{% url 'events:events-allevents' %}">Nearby Events</a>&nbsp; &nbsp;

    </nav>
        <br>
        <center><small><p># Please provide complete details of the event. Enter maximum characteristics of the event in the Event type field.</p></small></center>

    <br>
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
            <center><h3 class="card-title">Add Event Form</h3></center>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <br>
                <button type="submit" class="btn btn-primary btn-block">Add Event</button>
            </form>
            </div>
        </div>
        </div>
    </div>
    </div>
    
{% endblock body %}

src/templates/allevents.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

{% endblock head %}

{% block body %}
    <div class="container">
    <br>
    <a href="{% url 'events:events-home' %}" class="btn btn-danger">Home</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'events:events-addevent' %}" class="btn btn-danger">Add Event</a>
    {%endif%}
        <section class="section-buy-sell" style="padding: 2% 5% 10% 5%;">
            <div class="row mt-3">
                {% for event in allevents %}
                    {% if event.is_active %}
                        <div class="col-md-3" style="margin-top:20px; margin-right: 80px;">
                            <div class="card buy-card shadow" style="width: 18rem; ">
                                <img src="{{ event.poster.url }}" class="card-img-top" style="height: 350px;">
                                <div class="card-body">
                                    <h6 class="card-title"><strong> {{ event.name }} </strong></h6>
                                    <p class="small text-muted">Organized By: {{ event.organizer }}</p>
                                    <center><a href="{% url 'events:events-eventinfo' event.id %}"><button class="btn btn-outline-info">Information</button></a><center>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                   
                {% endfor %}
            </div>
                    
        </section>
    </div>

{% endblock body %} 

src/templates/development.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <title>Happening Free - Development</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock head %}


{% block body %}
<br>
    <div class="container">
    <a href="{% url 'events:events-home' %}" class="btn btn-danger" >BacktoHome</a><br><br>
    
        <div class="jumbotron center">
            <strong><center><h1 style="color:black;"> In Development </h1></center></strong><br>
            <center><h4>Sorry. We are still working on this part of the application.</h4></center>
        </div>
    </div>
{% endblock body %}

src/templates/eventinfo.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <title>Happening Free - {{ event.name }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/final.css' %}">


{% endblock head %}

{% block body %}
<br>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="btn btn-danger" href="{% url 'events:events-home' %}">Home</a>&nbsp; &nbsp;
        </nav>

        <br>
        <section class="section-buy-info">
            <div class="row">
                <div class="col-md-8">
                    <div class="image-container shadow">
                        <img src="{{ event.poster.url }}" class="buy-image" alt="machine">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="text-container shadow">
                        <h2><strong> {{ event.name }}</strong></h2>
                    <div class="table-data">
                            <table class="table">
                                <tbody>
                                    <tr style="font-size: 17px;">
                                    <th scope="row">Organizer: </th>
                                    <td>{{ event.organizer.first_name }} {{ event.organizer.last_name }}</td>
                                    </tr>
                                    <tr style="font-size: 17px;">
                                    <th scope="row">Contact: </th>
                                    <td>+91 {{ event.contact_number }}</td>
                                    </tr>
                                    <tr style="font-size: 17px;">
                                    <th scope="row">Date: </th>
                                    <td> {{ event.event_date }}</td>
                                    </tr>
                                    <tr style="font-size: 17px;">
                                    <th scope="row">Address: </th>
                                    <td> {{ event.address }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <br>
                    {% if request.user.is_authenticated %}
                        {% if event.organizer == request.user %}
                            <center><button type="button" class="btn btn-primary" disabled>Owner</button></center>
                        {%else%}
                            {% if present %}
                                <center><button type="button" class="btn btn-primary" disabled>Joined</button></center>
                            {% else %}
                                <center><a class="btn btn-danger" href="{% url 'events:events-eventjoin' event.id %}" style="align:right;">Join</a><center>                  
                            {% endif %}
                        {% endif %}
                    {% else %}
                         <center><a class="btn btn-danger" href="{% url 'events:events-eventjoin' event.id %}" style="align:right;">Login To Join</a><center>
                    {% endif %}
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col">
                    <div class="product-details-container shadow">
                        <h5 class="product-details"><strong>Event Information</strong></h5>
                        <hr>
                        <h6>{{ event.description }}</h6>
                    </div>
                </div>
            </div>
        </section>

    
    <footer class="page-footer font-small mdb-color lighten-3 pt-4">
        <small><div class="footer-copyright text-center py-3">© Copyright: The content and images used on this site are copyright protected and copyrights vests with the respective owners. The usage of the content and images on this website is intended to promote the works and no endorsement of the artist shall be implied. Unauthorized use is prohibited and punishable by law.
        </div></small>
    </footer> 

    </div>

            {% block js %}
            <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
            <script src="{% static 'js/bootstrap.js' %}"></script>
            {% endblock js %}
{% endblock body %}

src/templates/eventjoin.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <title>Happening Free</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
{% endblock head %}

{% block body %}
<br>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="btn btn-danger" href="{% url 'events:events-home' %}">Home</a>&nbsp; &nbsp;
        </nav>
        <br>
        <div class="jumbotron">
            <h2>{{ message }}</h2>
        </div>
    </div>
{% endblock body %}

src/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/queries.css' %}">
    <title>Happening Free - {{ title }}</title>
{% endblock head %}

{% block body %}
    <header>
        <nav>
            <div class="row">
                <img src="{% static 'css/img/logo.png' %}" class="logo">
                <ul class="main-nav">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'events:events-profile' %}">Profile</a></li>
                        <li><a href="{% url 'events:events-addevent' %}">Organize</a></li>
                        <li><a href="{% url 'events:events-logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'events:events-login' %}">Log in</a></li>
                        <li><a href="{% url 'events:events-signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
                </div>
        </nav> 
        <div class="blog-text-box">
            <h1>Happening things around you is waiting.</h1> <br>
            <a class="btn btn-full" href="{% url 'events:events-allevents' %}">Nearby events</a>
            {% if request.user.is_authenticated %}
                <a class="btn btn-full" href="{% url 'events:events-recommended' %}">Recommended events</a>
            {% endif %} 
        </div>
    </header>

            <section class="section-steps" id="works">
                <div class="row">
                    <h2>How it works &mdash; Simple as 1, 2, 3</h2>
                </div>
                <div class="row">
                    <div class="col span-1-of-2 steps-box">
                        <img src="{% static 'css/img/mobile.jpg' %}" alt="Omnifood app on iPhone" class="app-screen js--wp-2">
                    </div>
                    <div class="col span-1-of-2 steps-box">
                        <div class="works-step clearfix">
                            <div>1</div>
                            <p>Choose the Event as per your interest.</p>
                        </div>
                        <div class="works-step clearfix">
                            <div>2</div>
                            <p>Contact with the organiser and ask for details.</p>
                        </div>
                        <div class="works-step clearfix">
                            <div>3</div>
                            <p>Set as a confirmation if you're willing to attend.</p>
                        </div>
                        
                        <a href="{% url 'events:events-inprogress' %}" class="btn-app"><img src="{% static 'css/img/download-app.svg' %}" alt="App Store Button"></a>
                        <a href="{% url 'events:events-inprogress' %}" class="btn-app"><img src="{% static 'css/img/download-app-android.png' %}" alt="Play Store Button"></a>
                    </div>
                </div>
            </section>
            </body>

            <section class="section-features js--section-features" id="features">
            <div class="row">
                <h2>Meet new people &mdash; Meet new groups</h2>
                <p class="long-copy">
                    Hello, we're happening free, your new premium place to hangout and make new friends. We know you're always busy. No me time for yourself. So let us take care of that, we're really good at it, we promise!
                </p>
            </div>
            <br>
            <div class="row js--wp-1">
                <div class="col span-1-of-4 box">
                    <center><i class="ion-ios-infinite-outline icon-big"></i>
                    <h3>Up to 365 days/year</h3></center>
                    <p>
                        Never feel bored again! We really mean that. Our plans include up to 365 days/year. You can also choose to plan according to you, more flexible if that's your style.
                    </p>
                </div>
                <div class="col span-1-of-4 box">
                    <center><i class="ion-ios-stopwatch-outline icon-big"></i>
                    <h3>Plan in a minute</h3></center>
                    <p>
                        You're only minutes away to kill your boredom and organize a house party at your place and order super healthy meals right to your home. We try to make your weekend much more happening.
                    </p>
                </div>
                <div class="col span-1-of-4 box">
                    <center><i class="ion-ios-nutrition-outline icon-big"></i>
                    <h3>Let's cook together</h3></center>
                    <p>
                        Let's bring fresh vegetables, organic and plan for a picnic. Plan a trekking to a fort and cook with unknowns. Good for enjoying peaceful environment!
                    </p>
                </div>
                <div class="col span-1-of-4 box">
                    <center><i class="ion-ios-cart-outline icon-big"></i>
                    <h3>Shop together</h3></center>
                    <p>
                        We don't limit your creativity, which means you can plan to shop together and organize an event to shop. No one for a movie? Organize a event? It's up to you!
                    </p>
                </div>
            </div>   
        </section>


        <section class="section-testimonials">
            <div class="row">
                <h2>Our customers reviews are important</h2>
            </div>
            <div class="row">
                <div class="col span-1-of-3">
                    <blockquote>
                    <center><cite><img src="{% static 'img/customer-1.jpg' %}" style = "width: 200px; border-radius: 30%;" alt="Customer 3 photo"></cite></center><br>
                        Happening Free is just awesome! I recently moved to Pune and this website helped me making new friends and exploring this place, so Happening Free is a life-saver. Now that I got used to it, I couldn't live without planning a event in weekend.
                    </blockquote>
                </div>
                <div class="col span-1-of-3">
                    <blockquote>
                    <center><cite><img src="{% static 'img/customer-2.jpg' %}" style = "width: 200px; border-radius: 30%;" alt="Customer 3 photo"></cite></center><br>
                       Inexpensive, healthy and good quality events, right in your place. We have lots of choice to hangout but this media helps in improvising my introvert behvaiour. Me and my family are so in love!
                    </blockquote>
                </div>
                <div class="col span-1-of-3">
                    <blockquote>
                    <center><cite><img src="{% static 'img/man1.jpg' %}" style = "width: 200px; height: 100px; border-radius: 30%;" alt="Customer 3 photo"></cite></center><br>
I was looking for a quick and easy place to find in Delhi to hangout. I tried a lot of them and ended up with Happening Free. Best place to organize event in Delhi. Keep up the great work!
                    </blockquote>
                </div>
            </div>
        </section>



            <section class="section-form">
                <div class="row">
                    <h2>We're happy to hear from you</h2>
                </div>
                <div class="row">
                    <form method="post" action="#" class="contact-form">
                        <div class="row">
                            <div class="col span-1-of-3">
                                <label for="name">Name</label>
                            </div>
                            <div class="col span-2-of-3">
                                <input type="text" name="name" id="name" placeholder="Your name" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col span-1-of-3">
                                <label for="email">Email</label>
                            </div>
                            <div class="col span-2-of-3">
                                <input type="email" name="email" id="email" placeholder="Your email" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col span-1-of-3">
                                <label for="find-us">How did you find us?</label>
                            </div>
                            <div class="col span-2-of-3">
                                <select name="find-us" id="find-us">
                                    <option value="friends" selected>Friends</option>
                                    <option value="search">Search engine</option>
                                    <option value="ad">Advertisement</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col span-1-of-3">
                                <label>Newsletter?</label>
                            </div>
                            <div class="col span-2-of-3">
                                <input type="checkbox" name="news" id="news" checked> Yes, please
                            </div>
                        </div>
                        <div class="row">
                            <div class="col span-1-of-3">
                                <label>Drop us a line</label>
                            </div>
                            <div class="col span-2-of-3">
                                <textarea name="message" placeholder="Your message"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col span-1-of-3">
                                <label>&nbsp;</label>
                            </div>
                            <br>
                            <a href="{% url 'events:events-inprogress' %}" class=" btn btn-danger" style="background-color: grey;">Submit</a>
                        </div>
                        
                    </form>
                    
                </div>
            </section>
        <!--
        
        
            <section class="section-plans js--section-plans" id="plans">
                <div class="row">
                    <h2>Events near you</h2>
                </div>
                <div class="row">
    
                </div>
            </section>
        -->

            <footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-info">
                    <h1>Happening Free</h1>
                    <p>The content and images used on this site are copyright protected and copyrights vests with the respective owners. The usage of the content and images on this website is intended to promote the works and no endorsement of the artist shall be implied. Unauthorized use is prohibited and punishable by law.</p>
                </div>

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h4>Contact Us</h4>
                    <p>
                        Loni Kalbhor<br>
                        Pune, Maharashtra<br>
                        412201<br>
                        <strong>Phone:</strong> +91 99999 88888<br>
                        <strong>Email:</strong> happeningfree@example.com<br>
                    </p>
                    <br>
                    <div class="social-links">
                        <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fab fa-facebook"></i></a>
                        <a href="#" class="instagram"><i class="fab fa-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="fab fa-linkedin-in"></i></a>
                    </div>

                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong>Happening Free</strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=TheEvent
            -->
            Designed by ASHRAY PARMAR </a>
        </div>
    </div>
</footer>

{% endblock body %}

src/templates/myevents.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

{% endblock head %}

{% block body %}
    <div class="container">
    <br>
    <a href="{% url 'events:events-home' %}" class="btn btn-danger">Home</a>
    <a href="{% url 'events:events-profile' %}" class="btn btn-danger">Profile</a>
        <section class="section-buy-sell" style="padding: 2% 5% 10% 5%;">
            <div class="row mt-3">
                {% for event in events %}
                    {% if event.is_active %}
                        <div class="col-md-3" style="margin-top:20px; margin-right: 80px;">
                            <div class="card buy-card shadow" style="width: 18rem; ">
                                <img src="{{ event.poster.url }}" class="card-img-top" style="height: 350px;">
                                <div class="card-body">
                                    <center><h5 class="card-title"><strong> {{ event.name }} </strong></h5></center>
                                    <a href="{% url 'events:events-eventdelete' event.id %}"><button class="btn btn-outline-info">Delete</button></a>
                                    <a href="{% url 'events:events-participants' event.id %}"><button class="btn btn-outline-info">Participants</button></a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                   
                {% endfor %}
            </div>
                    
        </section>
    </div>

{% endblock body %} 

src/templates/participants.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

{% endblock head %}

{% block body %}
<br>
    <div class="container">
    <a href="{% url 'events:events-home' %}" class="btn btn-danger">Home</a>
    <a href="{% url 'events:events-myevents' %}" class="btn btn-danger">Your Events</a>
    </div>
    <br>
    <div class="container">
        {% if request.user == event.organizer %}

        <center><h1 class="display-4">Participants List</h1></center>
        <br>
        
            <ul>
                {% for part in participants %}
                    <h3><li>{{ part }}</li></h3>
                {% endfor %}
            </ul>
        {% else %}
            <center><h1 class="display-4">Sorry. you didn't organize this event.</h1></center>
        {% endif %}
    </div>   
    
{% endblock body %}

src/templates/recommendation.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

{% endblock head %}

{% block body %}
    <div class="container">
    <br>
    <a href="{% url 'events:events-home' %}" class="btn btn-danger">Home</a>
    <a href="{% url 'events:events-allevents' %}" class="btn btn-danger">All Events</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'events:events-addevent' %}" class="btn btn-danger">Add Event</a>
    {%endif%}
        <section class="section-buy-sell" style="padding: 2% 5% 10% 5%;">
            <div class="row mt-3">
                {% for event in event_list %}
                    {% if event.organizer == request.user %}
                    {% else %}
                        {% if event.is_active %}
                            <div class="col-md-3" style="margin-top:20px; margin-right: 80px;">
                                <div class="card buy-card shadow" style="width: 18rem; ">
                                    <img src="{{ event.poster.url }}" class="card-img-top" style="height: 350px;">
                                    <div class="card-body">
                                        <h6 class="card-title"><strong> {{ event.name }} </strong></h6>
                                        <p class="small text-muted">Organized By: {{ event.organizer }}</p>
                                        <center><a href="{% url 'events:events-eventinfo' event.id %}"><button class="btn btn-outline-info">Information</button></a><center>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
                    
        </section>
    </div>

{% endblock body %} 

src/templates/signup.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <title>Sign Up</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/backdrop.css' %}">
{% endblock head %}

{% block body %}
<br>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
            <a class="btn btn-danger" href="{% url 'events:events-home' %}">Home</a>&nbsp; &nbsp;
    </nav>
    <br>
            <center><small><p># Please provide complete details if possible. Enter more number of interests so that we can suggest you better events based on the same.</p></small></center>
    <br>
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
            <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
            </div>
            <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'events:events-login' %}">Log in</a>
            </div>
        </div>
        </div>
    </div>
    </div>
{% endblock body %}